<?php

/**
 * @file Google Civic module
 * Responsible for Google Civic Drupal hook implementations.
 */

/**
 * Implements hook_menu().
 */
function google_civic_menu() {
  $items['admin/config/services/google_civic'] = array(
    'title' => 'Google Civic',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_civic_settings_form'),
    'access arguments' => array('administer google civic'),
    'description' => t('API settings'),
    'file' => 'google_civic.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['google_civic/voterinfo'] = array(
    'title' => 'Where Do I Vote?',
    'page callback' => 'google_civic_voterinfo',
    'access arguments' => array('view google civic voterinfo'),
    'file' => 'google_civic.voterinfo.inc',
    'description' => t('Find your polling place'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function google_civic_permission() {
  $perms = array(
    'administer google civic' => array(
      'title' => t('administer google civic'),
      'description' => t('TODO Add a description for \'administer google civic\''),
    ),
    'view google civic voterinfo' => array(
      'title' => t('view google civic voterinfo'),
      'description' => t('TODO Add a description for \'view google civic voterinfo\''),
    ),
  );

  return $perms;
}

/**
 * Implements hook_block_info().
 */
function google_civic_block_info() {
  $blocks = array();
  $blocks['google_civic_address'] = array(
    'info' => t('Google Civic Address Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function google_civic_block_view($delta) {
  if ($delta == 'google_civic_address') {
    drupal_add_css(drupal_get_path('module', 'google_civic') .
      '/css/google_civic.css');

    $block['subject'] = t('Find Your Polling Place');
    $block['content'] = drupal_get_form('google_civic_address_form', 'block');
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function google_civic_theme($existing, $type, $theme, $path) {
  $tpls_dir = drupal_get_path('module', 'google_civic') . '/tpls';

  $templates = array(
    'google_civic_voterinfo' => array(
      'variables' => array(
        'headline' => '',
        'locations' => '',
        'early_locations' => '',
        'map' => '',
        'election_info_link' => '',
        'address_form' => '',
      ),
      'path' => $tpls_dir,
      'template' => 'google-civic-voterinfo',
    ),
    'google_civic_locations' => array(
      'variables' => array(
        'locations' => '',
        'class_prefix' => '',
      ),
      'path' => $tpls_dir,
      'template' => 'google-civic-locations',
    ),
  );

  return $templates;
}

/** Form wrapping */

/**
 * Form builder function for address input form for polling place locator.
 * @param string $style
 *  The style of form to display: either 'page' or 'block'
 * @see _google_civic_address_form (google_civic.forms.inc).
 */
function google_civic_address_form(&$form_state, $style = 'page') {
  module_load_include('inc', 'google_civic', 'google_civic.forms');
  return _google_civic_address_form($style);
}
