<?php

/**
 * @file Google Civic module
 * Responsible for Google Civic Drupal hook implementations.
 */

/**
 * Implements Drupal's hook_menu().
 */
function google_civic_menu() {
  $items['admin/settings/google_civic'] = array(
    'title' => 'Google Civic Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_civic_settings_form'),
    'access arguments' => array('administer google civic'),
    'description' => t('Google Civic API settings'),
    'file' => 'google_civic.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['google_civic/voterinfo'] = array(
    'title' => 'Where Do I Vote?',
    'page callback' => 'google_civic_voterinfo',
    'access arguments' => array('view google civic voterinfo'),
    'file' => 'google_civic.voterinfo.inc',
    'description' => t('Find your polling place'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements Drupal's hook_perm().
 */
function google_civic_perm() {
  $perms = array(
    'administer google civic',
    'view google civic voterinfo'
  );

  return $perms;
}

/**
 * Implements Drupal's hook_block().
 */
function google_civic_block($op = 'list', $delta = 0, $edit = array()) {
  module_load_include('inc', 'google_civic', 'google_civic.block');

  switch ($op) {
    case 'list':
      return google_civic_block_list();
    case 'configure':
    case 'save':
      break;
    case 'view':
      return google_civic_block_view($delta);
    default:
      break;
  }
}

/**
 * Implements Drupal's hook_theme().
 */
function google_civic_theme($existing, $type, $theme, $path) {
  $tpls_dir = drupal_get_path('module', 'google_civic') . '/tpls';

  $templates = array(
    'google_civic_voterinfo' => array(
      'arguments' => array(
        'headline' => '',
        'locations' => '',
        'early_locations' => '',
        'map' => '',
        'election_info_link' => '',
        'address_form' => '',
      ),
      'path' => $tpls_dir,
      'template' => 'google-civic-voterinfo',
    ),
    'google_civic_locations' => array(
      'arguments' => array(
        'locations' => '',
        'class_prefix' => '',
      ),
      'path' => $tpls_dir,
      'template' => 'google-civic-locations',
    ),
  );

  return $templates;
}

/** Form wrapping */

/**
 * @see _google_civic_address_form (google_civic.forms.inc).
 */
function google_civic_address_form() {
  module_load_include('inc', 'google_civic', 'google_civic.forms');
  return _google_civic_address_form();
}

